# Generated by Django 4.1.2 on 2022-10-23 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unescoo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='description',
        ),
        migrations.RemoveField(
            model_name='site',
            name='justification',
        ),
    ]
